name: Generate Podcasts feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Run feed generator
        uses: paulnasdaq/podcast-generator@main
        
        
